/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TournamentStatus = IDL.Variant({
  'upcoming' : IDL.Null,
  'complete' : IDL.Null,
  'ongoing' : IDL.Null,
});
export const TransactionType = IDL.Variant({
  'deposit' : IDL.Null,
  'withdrawal' : IDL.Null,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'imageUrl' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Tournament = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : IDL.Int,
  'status' : TournamentStatus,
  'title' : IDL.Text,
  'playerCount' : IDL.Nat,
  'description' : IDL.Text,
  'gameMode' : IDL.Text,
  'entryFee' : IDL.Nat,
  'maxPlayers' : IDL.Nat,
  'prizePool' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'principal' : IDL.Principal,
  'referralCode' : IDL.Text,
  'username' : IDL.Text,
  'isBlocked' : IDL.Bool,
  'walletBalance' : IDL.Nat,
  'ffUid' : IDL.Text,
});
export const AppSettings = IDL.Record({
  'upiDetails' : IDL.Text,
  'announcementText' : IDL.Text,
  'refundPolicy' : IDL.Text,
  'privacyPolicy' : IDL.Text,
  'appName' : IDL.Text,
  'minWithdraw' : IDL.Nat,
  'termsAndConditions' : IDL.Text,
  'supportContact' : IDL.Text,
  'referralBonus' : IDL.Nat,
});
export const TournamentResult = IDL.Record({
  'playerId' : IDL.Principal,
  'prize' : IDL.Nat,
  'position' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'blockUser' : IDL.Func([IDL.Principal], [], []),
  'createNotification' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'createTournament' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        TournamentStatus,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'createWalletTransaction' : IDL.Func(
      [IDL.Principal, IDL.Nat, TransactionType],
      [IDL.Nat],
      [],
    ),
  'getAllNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getAllTournaments' : IDL.Func([], [IDL.Vec(Tournament)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getSettings' : IDL.Func([], [IDL.Opt(AppSettings)], ['query']),
  'getTournamentParticipants' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getTournamentResults' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(TournamentResult)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinTournament' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setTournamentResults' : IDL.Func(
      [IDL.Nat, IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat, IDL.Principal))],
      [],
      [],
    ),
  'unblockUser' : IDL.Func([IDL.Principal], [], []),
  'updateSettings' : IDL.Func([AppSettings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TournamentStatus = IDL.Variant({
    'upcoming' : IDL.Null,
    'complete' : IDL.Null,
    'ongoing' : IDL.Null,
  });
  const TransactionType = IDL.Variant({
    'deposit' : IDL.Null,
    'withdrawal' : IDL.Null,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'imageUrl' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Tournament = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : IDL.Int,
    'status' : TournamentStatus,
    'title' : IDL.Text,
    'playerCount' : IDL.Nat,
    'description' : IDL.Text,
    'gameMode' : IDL.Text,
    'entryFee' : IDL.Nat,
    'maxPlayers' : IDL.Nat,
    'prizePool' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'principal' : IDL.Principal,
    'referralCode' : IDL.Text,
    'username' : IDL.Text,
    'isBlocked' : IDL.Bool,
    'walletBalance' : IDL.Nat,
    'ffUid' : IDL.Text,
  });
  const AppSettings = IDL.Record({
    'upiDetails' : IDL.Text,
    'announcementText' : IDL.Text,
    'refundPolicy' : IDL.Text,
    'privacyPolicy' : IDL.Text,
    'appName' : IDL.Text,
    'minWithdraw' : IDL.Nat,
    'termsAndConditions' : IDL.Text,
    'supportContact' : IDL.Text,
    'referralBonus' : IDL.Nat,
  });
  const TournamentResult = IDL.Record({
    'playerId' : IDL.Principal,
    'prize' : IDL.Nat,
    'position' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'blockUser' : IDL.Func([IDL.Principal], [], []),
    'createNotification' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'createTournament' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          TournamentStatus,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'createWalletTransaction' : IDL.Func(
        [IDL.Principal, IDL.Nat, TransactionType],
        [IDL.Nat],
        [],
      ),
    'getAllNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getAllTournaments' : IDL.Func([], [IDL.Vec(Tournament)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getSettings' : IDL.Func([], [IDL.Opt(AppSettings)], ['query']),
    'getTournamentParticipants' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getTournamentResults' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(TournamentResult)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinTournament' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setTournamentResults' : IDL.Func(
        [IDL.Nat, IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat, IDL.Principal))],
        [],
        [],
      ),
    'unblockUser' : IDL.Func([IDL.Principal], [], []),
    'updateSettings' : IDL.Func([AppSettings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };