/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppSettings {
  'upiDetails' : string,
  'announcementText' : string,
  'refundPolicy' : string,
  'privacyPolicy' : string,
  'minDeposit' : bigint,
  'appName' : string,
  'minWithdraw' : bigint,
  'termsAndConditions' : string,
  'supportContact' : string,
  'referralBonus' : bigint,
}
export interface LeaderboardEntry {
  'playerName' : string,
  'prize' : bigint,
  'position' : bigint,
}
export interface Notification {
  'id' : bigint,
  'title' : string,
  'imageUrl' : string,
  'message' : string,
  'timestamp' : bigint,
}
export interface OpenPaymentRequest {
  'id' : bigint,
  'status' : string,
  'username' : string,
  'note' : string,
  'timestamp' : bigint,
  'upiId' : string,
  'phone' : string,
  'amount' : bigint,
  'approvedAmount' : bigint,
  'requestType' : string,
}
export interface PaymentRequest {
  'id' : bigint,
  'status' : PaymentRequestStatus,
  'username' : string,
  'userId' : Principal,
  'note' : string,
  'timestamp' : bigint,
  'upiId' : string,
  'amount' : bigint,
  'requestType' : PaymentRequestType,
}
export type PaymentRequestStatus = { 'pending' : null } |
  { 'rejected' : null } |
  { 'accepted' : null };
export type PaymentRequestType = { 'withdraw' : null } |
  { 'deposit' : null };
export interface PhoneUser {
  'referralCode' : string,
  'username' : string,
  'winningCash' : bigint,
  'passwordHash' : string,
  'ffName' : string,
  'phone' : string,
  'registeredAt' : bigint,
  'walletBalance' : bigint,
}
export interface PhoneUserView {
  'referralCode' : string,
  'username' : string,
  'winningCash' : bigint,
  'ffName' : string,
  'phone' : string,
  'registeredAt' : bigint,
  'walletBalance' : bigint,
}
export interface TournamentResult {
  'playerId' : Principal,
  'prize' : bigint,
  'position' : bigint,
}
export type TournamentStatus = { 'upcoming' : null } |
  { 'complete' : null } |
  { 'ongoing' : null };
export interface TournamentView {
  'id' : bigint,
  'startTime' : bigint,
  'status' : TournamentStatus,
  'title' : string,
  'minPlayers' : bigint,
  'playerCount' : bigint,
  'description' : string,
  'gameMode' : string,
  'entryFee' : bigint,
  'maxPlayers' : bigint,
  'prizePool' : bigint,
}
export type TransactionType = { 'deposit' : null } |
  { 'withdrawal' : null };
export interface UserProfile {
  'principal' : Principal,
  'referralCode' : string,
  'username' : string,
  'isBlocked' : boolean,
  'walletBalance' : bigint,
  'ffUid' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'blockUser' : ActorMethod<[Principal], undefined>,
  'createNotification' : ActorMethod<[string, string, string], undefined>,
  'createTournament' : ActorMethod<
    [
      string,
      string,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      TournamentStatus,
      string,
    ],
    bigint
  >,
  'createWalletTransaction' : ActorMethod<
    [Principal, bigint, TransactionType],
    bigint
  >,
  'getAllNotifications' : ActorMethod<[], Array<Notification>>,
  'getAllOpenPaymentRequests' : ActorMethod<[], Array<OpenPaymentRequest>>,
  'getAllPaymentRequests' : ActorMethod<[], Array<PaymentRequest>>,
  'getAllPhoneUsers' : ActorMethod<[], Array<PhoneUserView>>,
  'getAllTournaments' : ActorMethod<[], Array<TournamentView>>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLeaderboard' : ActorMethod<[bigint], Array<LeaderboardEntry>>,
  'getMyOpenPaymentRequests' : ActorMethod<[string], Array<OpenPaymentRequest>>,
  'getMyPaymentRequests' : ActorMethod<[], Array<PaymentRequest>>,
  'getPhoneUser' : ActorMethod<[string], [] | [PhoneUser]>,
  'getSettings' : ActorMethod<[], [] | [AppSettings]>,
  'getTournamentParticipants' : ActorMethod<[bigint], Array<Principal>>,
  'getTournamentResults' : ActorMethod<[bigint], Array<TournamentResult>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinTournament' : ActorMethod<[bigint], undefined>,
  'phoneUserExists' : ActorMethod<[string], boolean>,
  'registerPhoneUser' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setLeaderboard' : ActorMethod<
    [bigint, Array<[bigint, string, bigint]>],
    undefined
  >,
  'setTournamentResults' : ActorMethod<
    [bigint, Array<[bigint, bigint, Principal]>],
    undefined
  >,
  'submitOpenPaymentRequest' : ActorMethod<
    [string, string, bigint, string, string, string],
    bigint
  >,
  'submitPaymentRequest' : ActorMethod<
    [bigint, PaymentRequestType, string, string],
    bigint
  >,
  'unblockUser' : ActorMethod<[Principal], undefined>,
  'updateOpenPaymentStatus' : ActorMethod<[bigint, string, bigint], bigint>,
  'updatePaymentRequestStatus' : ActorMethod<
    [bigint, PaymentRequestStatus],
    undefined
  >,
  'updatePhoneUserBalance' : ActorMethod<[string, bigint], undefined>,
  'updatePhoneUserWinningCash' : ActorMethod<[string, bigint], undefined>,
  'updateSettings' : ActorMethod<[AppSettings], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];