/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TournamentStatus = IDL.Variant({
  'upcoming' : IDL.Null,
  'complete' : IDL.Null,
  'ongoing' : IDL.Null,
});
export const TransactionType = IDL.Variant({
  'deposit' : IDL.Null,
  'withdrawal' : IDL.Null,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'imageUrl' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const OpenPaymentRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'username' : IDL.Text,
  'note' : IDL.Text,
  'timestamp' : IDL.Int,
  'upiId' : IDL.Text,
  'phone' : IDL.Text,
  'amount' : IDL.Nat,
  'approvedAmount' : IDL.Nat,
  'requestType' : IDL.Text,
});
export const PaymentRequestStatus = IDL.Variant({
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
  'accepted' : IDL.Null,
});
export const PaymentRequestType = IDL.Variant({
  'withdraw' : IDL.Null,
  'deposit' : IDL.Null,
});
export const PaymentRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : PaymentRequestStatus,
  'username' : IDL.Text,
  'userId' : IDL.Principal,
  'note' : IDL.Text,
  'timestamp' : IDL.Int,
  'upiId' : IDL.Text,
  'amount' : IDL.Nat,
  'requestType' : PaymentRequestType,
});
export const PhoneUserView = IDL.Record({
  'referralCode' : IDL.Text,
  'username' : IDL.Text,
  'winningCash' : IDL.Nat,
  'ffName' : IDL.Text,
  'phone' : IDL.Text,
  'registeredAt' : IDL.Int,
  'walletBalance' : IDL.Nat,
});
export const TournamentView = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : IDL.Int,
  'status' : TournamentStatus,
  'title' : IDL.Text,
  'minPlayers' : IDL.Nat,
  'playerCount' : IDL.Nat,
  'description' : IDL.Text,
  'gameMode' : IDL.Text,
  'entryFee' : IDL.Nat,
  'maxPlayers' : IDL.Nat,
  'prizePool' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'principal' : IDL.Principal,
  'referralCode' : IDL.Text,
  'username' : IDL.Text,
  'isBlocked' : IDL.Bool,
  'walletBalance' : IDL.Nat,
  'ffUid' : IDL.Text,
});
export const LeaderboardEntry = IDL.Record({
  'playerName' : IDL.Text,
  'prize' : IDL.Nat,
  'position' : IDL.Nat,
});
export const PhoneUser = IDL.Record({
  'referralCode' : IDL.Text,
  'username' : IDL.Text,
  'winningCash' : IDL.Nat,
  'passwordHash' : IDL.Text,
  'ffName' : IDL.Text,
  'phone' : IDL.Text,
  'registeredAt' : IDL.Int,
  'walletBalance' : IDL.Nat,
});
export const AppSettings = IDL.Record({
  'upiDetails' : IDL.Text,
  'announcementText' : IDL.Text,
  'refundPolicy' : IDL.Text,
  'privacyPolicy' : IDL.Text,
  'minDeposit' : IDL.Nat,
  'appName' : IDL.Text,
  'minWithdraw' : IDL.Nat,
  'termsAndConditions' : IDL.Text,
  'supportContact' : IDL.Text,
  'referralBonus' : IDL.Nat,
});
export const TournamentResult = IDL.Record({
  'playerId' : IDL.Principal,
  'prize' : IDL.Nat,
  'position' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'blockUser' : IDL.Func([IDL.Principal], [], []),
  'createNotification' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'createTournament' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        TournamentStatus,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'createWalletTransaction' : IDL.Func(
      [IDL.Principal, IDL.Nat, TransactionType],
      [IDL.Nat],
      [],
    ),
  'getAllNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getAllOpenPaymentRequests' : IDL.Func(
      [],
      [IDL.Vec(OpenPaymentRequest)],
      ['query'],
    ),
  'getAllPaymentRequests' : IDL.Func([], [IDL.Vec(PaymentRequest)], ['query']),
  'getAllPhoneUsers' : IDL.Func([], [IDL.Vec(PhoneUserView)], ['query']),
  'getAllTournaments' : IDL.Func([], [IDL.Vec(TournamentView)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLeaderboard' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(LeaderboardEntry)],
      ['query'],
    ),
  'getMyOpenPaymentRequests' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(OpenPaymentRequest)],
      ['query'],
    ),
  'getMyPaymentRequests' : IDL.Func([], [IDL.Vec(PaymentRequest)], ['query']),
  'getPhoneUser' : IDL.Func([IDL.Text], [IDL.Opt(PhoneUser)], ['query']),
  'getSettings' : IDL.Func([], [IDL.Opt(AppSettings)], ['query']),
  'getTournamentParticipants' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getTournamentResults' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(TournamentResult)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinTournament' : IDL.Func([IDL.Nat], [], []),
  'phoneUserExists' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'registerPhoneUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setLeaderboard' : IDL.Func(
      [IDL.Nat, IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text, IDL.Nat))],
      [],
      [],
    ),
  'setTournamentResults' : IDL.Func(
      [IDL.Nat, IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat, IDL.Principal))],
      [],
      [],
    ),
  'submitOpenPaymentRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'submitPaymentRequest' : IDL.Func(
      [IDL.Nat, PaymentRequestType, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'unblockUser' : IDL.Func([IDL.Principal], [], []),
  'updateOpenPaymentStatus' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'updatePaymentRequestStatus' : IDL.Func(
      [IDL.Nat, PaymentRequestStatus],
      [],
      [],
    ),
  'updatePhoneUserBalance' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'updatePhoneUserWinningCash' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'updateSettings' : IDL.Func([AppSettings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TournamentStatus = IDL.Variant({
    'upcoming' : IDL.Null,
    'complete' : IDL.Null,
    'ongoing' : IDL.Null,
  });
  const TransactionType = IDL.Variant({
    'deposit' : IDL.Null,
    'withdrawal' : IDL.Null,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'imageUrl' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const OpenPaymentRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'username' : IDL.Text,
    'note' : IDL.Text,
    'timestamp' : IDL.Int,
    'upiId' : IDL.Text,
    'phone' : IDL.Text,
    'amount' : IDL.Nat,
    'approvedAmount' : IDL.Nat,
    'requestType' : IDL.Text,
  });
  const PaymentRequestStatus = IDL.Variant({
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const PaymentRequestType = IDL.Variant({
    'withdraw' : IDL.Null,
    'deposit' : IDL.Null,
  });
  const PaymentRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : PaymentRequestStatus,
    'username' : IDL.Text,
    'userId' : IDL.Principal,
    'note' : IDL.Text,
    'timestamp' : IDL.Int,
    'upiId' : IDL.Text,
    'amount' : IDL.Nat,
    'requestType' : PaymentRequestType,
  });
  const PhoneUserView = IDL.Record({
    'referralCode' : IDL.Text,
    'username' : IDL.Text,
    'winningCash' : IDL.Nat,
    'ffName' : IDL.Text,
    'phone' : IDL.Text,
    'registeredAt' : IDL.Int,
    'walletBalance' : IDL.Nat,
  });
  const TournamentView = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : IDL.Int,
    'status' : TournamentStatus,
    'title' : IDL.Text,
    'minPlayers' : IDL.Nat,
    'playerCount' : IDL.Nat,
    'description' : IDL.Text,
    'gameMode' : IDL.Text,
    'entryFee' : IDL.Nat,
    'maxPlayers' : IDL.Nat,
    'prizePool' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'principal' : IDL.Principal,
    'referralCode' : IDL.Text,
    'username' : IDL.Text,
    'isBlocked' : IDL.Bool,
    'walletBalance' : IDL.Nat,
    'ffUid' : IDL.Text,
  });
  const LeaderboardEntry = IDL.Record({
    'playerName' : IDL.Text,
    'prize' : IDL.Nat,
    'position' : IDL.Nat,
  });
  const PhoneUser = IDL.Record({
    'referralCode' : IDL.Text,
    'username' : IDL.Text,
    'winningCash' : IDL.Nat,
    'passwordHash' : IDL.Text,
    'ffName' : IDL.Text,
    'phone' : IDL.Text,
    'registeredAt' : IDL.Int,
    'walletBalance' : IDL.Nat,
  });
  const AppSettings = IDL.Record({
    'upiDetails' : IDL.Text,
    'announcementText' : IDL.Text,
    'refundPolicy' : IDL.Text,
    'privacyPolicy' : IDL.Text,
    'minDeposit' : IDL.Nat,
    'appName' : IDL.Text,
    'minWithdraw' : IDL.Nat,
    'termsAndConditions' : IDL.Text,
    'supportContact' : IDL.Text,
    'referralBonus' : IDL.Nat,
  });
  const TournamentResult = IDL.Record({
    'playerId' : IDL.Principal,
    'prize' : IDL.Nat,
    'position' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'blockUser' : IDL.Func([IDL.Principal], [], []),
    'createNotification' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'createTournament' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          TournamentStatus,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'createWalletTransaction' : IDL.Func(
        [IDL.Principal, IDL.Nat, TransactionType],
        [IDL.Nat],
        [],
      ),
    'getAllNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getAllOpenPaymentRequests' : IDL.Func(
        [],
        [IDL.Vec(OpenPaymentRequest)],
        ['query'],
      ),
    'getAllPaymentRequests' : IDL.Func(
        [],
        [IDL.Vec(PaymentRequest)],
        ['query'],
      ),
    'getAllPhoneUsers' : IDL.Func([], [IDL.Vec(PhoneUserView)], ['query']),
    'getAllTournaments' : IDL.Func([], [IDL.Vec(TournamentView)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLeaderboard' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(LeaderboardEntry)],
        ['query'],
      ),
    'getMyOpenPaymentRequests' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(OpenPaymentRequest)],
        ['query'],
      ),
    'getMyPaymentRequests' : IDL.Func([], [IDL.Vec(PaymentRequest)], ['query']),
    'getPhoneUser' : IDL.Func([IDL.Text], [IDL.Opt(PhoneUser)], ['query']),
    'getSettings' : IDL.Func([], [IDL.Opt(AppSettings)], ['query']),
    'getTournamentParticipants' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getTournamentResults' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(TournamentResult)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinTournament' : IDL.Func([IDL.Nat], [], []),
    'phoneUserExists' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'registerPhoneUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setLeaderboard' : IDL.Func(
        [IDL.Nat, IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text, IDL.Nat))],
        [],
        [],
      ),
    'setTournamentResults' : IDL.Func(
        [IDL.Nat, IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat, IDL.Principal))],
        [],
        [],
      ),
    'submitOpenPaymentRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'submitPaymentRequest' : IDL.Func(
        [IDL.Nat, PaymentRequestType, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'unblockUser' : IDL.Func([IDL.Principal], [], []),
    'updateOpenPaymentStatus' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'updatePaymentRequestStatus' : IDL.Func(
        [IDL.Nat, PaymentRequestStatus],
        [],
        [],
      ),
    'updatePhoneUserBalance' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'updatePhoneUserWinningCash' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'updateSettings' : IDL.Func([AppSettings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };