/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppSettings {
  'upiDetails' : string,
  'announcementText' : string,
  'refundPolicy' : string,
  'privacyPolicy' : string,
  'appName' : string,
  'minWithdraw' : bigint,
  'termsAndConditions' : string,
  'supportContact' : string,
  'referralBonus' : bigint,
}
export interface Notification {
  'id' : bigint,
  'title' : string,
  'imageUrl' : string,
  'message' : string,
  'timestamp' : bigint,
}
export interface LeaderboardEntry {
  'position' : bigint,
  'playerName' : string,
  'prize' : bigint,
}
export interface Tournament {
  'id' : bigint,
  'startTime' : bigint,
  'status' : TournamentStatus,
  'title' : string,
  'playerCount' : bigint,
  'description' : string,
  'gameMode' : string,
  'entryFee' : bigint,
  'maxPlayers' : bigint,
  'minPlayers' : bigint,
  'prizePool' : bigint,
}
export interface TournamentResult {
  'playerId' : Principal,
  'prize' : bigint,
  'position' : bigint,
}
export type TournamentStatus = { 'upcoming' : null } |
  { 'complete' : null } |
  { 'ongoing' : null };
export type TransactionType = { 'deposit' : null } |
  { 'withdrawal' : null };
export interface UserProfile {
  'principal' : Principal,
  'referralCode' : string,
  'username' : string,
  'isBlocked' : boolean,
  'walletBalance' : bigint,
  'ffUid' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'blockUser' : ActorMethod<[Principal], undefined>,
  'createNotification' : ActorMethod<[string, string, string], undefined>,
  'createTournament' : ActorMethod<
    [string, string, bigint, bigint, bigint, bigint, bigint, TournamentStatus, string],
    bigint
  >,
  'createWalletTransaction' : ActorMethod<
    [Principal, bigint, TransactionType],
    bigint
  >,
  'getAllNotifications' : ActorMethod<[], Array<Notification>>,
  'getAllTournaments' : ActorMethod<[], Array<Tournament>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getSettings' : ActorMethod<[], [] | [AppSettings]>,
  'getTournamentParticipants' : ActorMethod<[bigint], Array<Principal>>,
  'getTournamentResults' : ActorMethod<[bigint], Array<TournamentResult>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinTournament' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setTournamentResults' : ActorMethod<
    [bigint, Array<[bigint, bigint, Principal]>],
    undefined
  >,
  'unblockUser' : ActorMethod<[Principal], undefined>,
  'updateSettings' : ActorMethod<[AppSettings], undefined>,
  'getLeaderboard' : ActorMethod<[bigint], Array<LeaderboardEntry>>,
  'setLeaderboard' : ActorMethod<[bigint, Array<[bigint, string, bigint]>], undefined>,
  'adminAdjustWallet' : ActorMethod<[Principal, bigint, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];