/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface LeaderboardEntry {
    playerName: string;
    prize: bigint;
    position: bigint;
}
export interface TournamentView {
    id: bigint;
    startTime: bigint;
    status: TournamentStatus;
    title: string;
    minPlayers: bigint;
    playerCount: bigint;
    description: string;
    gameMode: string;
    entryFee: bigint;
    maxPlayers: bigint;
    prizePool: bigint;
}
export interface TournamentResult {
    playerId: Principal;
    prize: bigint;
    position: bigint;
}
export interface PhoneUser {
    referralCode: string;
    username: string;
    winningCash: bigint;
    passwordHash: string;
    ffName: string;
    phone: string;
    registeredAt: bigint;
    walletBalance: bigint;
}
export interface AppSettings {
    upiDetails: string;
    announcementText: string;
    refundPolicy: string;
    privacyPolicy: string;
    minDeposit: bigint;
    appName: string;
    minWithdraw: bigint;
    termsAndConditions: string;
    supportContact: string;
    referralBonus: bigint;
}
export interface PhoneUserView {
    referralCode: string;
    username: string;
    winningCash: bigint;
    ffName: string;
    phone: string;
    registeredAt: bigint;
    walletBalance: bigint;
}
export interface Notification {
    id: bigint;
    title: string;
    imageUrl: string;
    message: string;
    timestamp: bigint;
}
export interface PaymentRequest {
    id: bigint;
    status: PaymentRequestStatus;
    username: string;
    userId: Principal;
    note: string;
    timestamp: bigint;
    upiId: string;
    amount: bigint;
    requestType: PaymentRequestType;
}
export interface OpenPaymentRequest {
    id: bigint;
    status: string;
    username: string;
    note: string;
    timestamp: bigint;
    upiId: string;
    phone: string;
    amount: bigint;
    approvedAmount: bigint;
    requestType: string;
}
export interface UserProfile {
    principal: Principal;
    referralCode: string;
    username: string;
    isBlocked: boolean;
    walletBalance: bigint;
    ffUid: string;
}
export enum PaymentRequestStatus {
    pending = "pending",
    rejected = "rejected",
    accepted = "accepted"
}
export enum PaymentRequestType {
    withdraw = "withdraw",
    deposit = "deposit"
}
export enum TournamentStatus {
    upcoming = "upcoming",
    complete = "complete",
    ongoing = "ongoing"
}
export enum TransactionType {
    deposit = "deposit",
    withdrawal = "withdrawal"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    blockUser(userId: Principal): Promise<void>;
    createNotification(title: string, message: string, imageUrl: string): Promise<void>;
    createTournament(title: string, gameMode: string, startTime: bigint, entryFee: bigint, prizePool: bigint, maxPlayers: bigint, minPlayers: bigint, status: TournamentStatus, description: string): Promise<bigint>;
    createWalletTransaction(userId: Principal, amount: bigint, transactionType: TransactionType): Promise<bigint>;
    getAllNotifications(): Promise<Array<Notification>>;
    getAllOpenPaymentRequests(): Promise<Array<OpenPaymentRequest>>;
    getAllPaymentRequests(): Promise<Array<PaymentRequest>>;
    getAllPhoneUsers(): Promise<Array<PhoneUserView>>;
    getAllTournaments(): Promise<Array<TournamentView>>;
    getAllUsers(): Promise<Array<UserProfile>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getLeaderboard(tournamentId: bigint): Promise<Array<LeaderboardEntry>>;
    getMyOpenPaymentRequests(phone: string): Promise<Array<OpenPaymentRequest>>;
    getMyPaymentRequests(): Promise<Array<PaymentRequest>>;
    getPhoneUser(phone: string): Promise<PhoneUser | null>;
    getSettings(): Promise<AppSettings | null>;
    getTournamentParticipants(tournamentId: bigint): Promise<Array<Principal>>;
    getTournamentResults(tournamentId: bigint): Promise<Array<TournamentResult>>;
    getUserProfile(userPrincipal: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    joinTournament(tournamentId: bigint): Promise<void>;
    phoneUserExists(phone: string): Promise<boolean>;
    registerPhoneUser(phone: string, username: string, ffName: string, passwordHash: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setLeaderboard(tournamentId: bigint, entries: Array<[bigint, string, bigint]>): Promise<void>;
    setTournamentResults(tournamentId: bigint, positions: Array<[bigint, bigint, Principal]>): Promise<void>;
    submitOpenPaymentRequest(phone: string, username: string, amount: bigint, requestType: string, note: string, upiId: string): Promise<bigint>;
    submitPaymentRequest(amount: bigint, requestType: PaymentRequestType, note: string, upiId: string): Promise<bigint>;
    unblockUser(userId: Principal): Promise<void>;
    updateOpenPaymentStatus(requestId: bigint, newStatus: string, approvedAmount: bigint): Promise<bigint>;
    updatePaymentRequestStatus(requestId: bigint, newStatus: PaymentRequestStatus): Promise<void>;
    updatePhoneUserBalance(phone: string, balance: bigint): Promise<void>;
    updatePhoneUserWinningCash(phone: string, amount: bigint): Promise<void>;
    updateSettings(newSettings: AppSettings): Promise<void>;
}
import type { AppSettings as _AppSettings, PaymentRequest as _PaymentRequest, PaymentRequestStatus as _PaymentRequestStatus, PaymentRequestType as _PaymentRequestType, PhoneUser as _PhoneUser, TournamentStatus as _TournamentStatus, TournamentView as _TournamentView, TransactionType as _TransactionType, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async blockUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.blockUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.blockUser(arg0);
            return result;
        }
    }
    async createNotification(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createNotification(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNotification(arg0, arg1, arg2);
            return result;
        }
    }
    async createTournament(arg0: string, arg1: string, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint, arg7: TournamentStatus, arg8: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTournament(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_TournamentStatus_n3(this._uploadFile, this._downloadFile, arg7), arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTournament(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_TournamentStatus_n3(this._uploadFile, this._downloadFile, arg7), arg8);
            return result;
        }
    }
    async createWalletTransaction(arg0: Principal, arg1: bigint, arg2: TransactionType): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createWalletTransaction(arg0, arg1, to_candid_TransactionType_n5(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createWalletTransaction(arg0, arg1, to_candid_TransactionType_n5(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async getAllNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNotifications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNotifications();
            return result;
        }
    }
    async getAllOpenPaymentRequests(): Promise<Array<OpenPaymentRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOpenPaymentRequests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOpenPaymentRequests();
            return result;
        }
    }
    async getAllPaymentRequests(): Promise<Array<PaymentRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPaymentRequests();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPaymentRequests();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPhoneUsers(): Promise<Array<PhoneUserView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPhoneUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPhoneUsers();
            return result;
        }
    }
    async getAllTournaments(): Promise<Array<TournamentView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTournaments();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTournaments();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsers(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeaderboard(arg0: bigint): Promise<Array<LeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard(arg0);
            return result;
        }
    }
    async getMyOpenPaymentRequests(arg0: string): Promise<Array<OpenPaymentRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyOpenPaymentRequests(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyOpenPaymentRequests(arg0);
            return result;
        }
    }
    async getMyPaymentRequests(): Promise<Array<PaymentRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyPaymentRequests();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyPaymentRequests();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPhoneUser(arg0: string): Promise<PhoneUser | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPhoneUser(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPhoneUser(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSettings(): Promise<AppSettings | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettings();
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettings();
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTournamentParticipants(arg0: bigint): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTournamentParticipants(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTournamentParticipants(arg0);
            return result;
        }
    }
    async getTournamentResults(arg0: bigint): Promise<Array<TournamentResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTournamentResults(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTournamentResults(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async joinTournament(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.joinTournament(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinTournament(arg0);
            return result;
        }
    }
    async phoneUserExists(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.phoneUserExists(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.phoneUserExists(arg0);
            return result;
        }
    }
    async registerPhoneUser(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerPhoneUser(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerPhoneUser(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setLeaderboard(arg0: bigint, arg1: Array<[bigint, string, bigint]>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setLeaderboard(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setLeaderboard(arg0, arg1);
            return result;
        }
    }
    async setTournamentResults(arg0: bigint, arg1: Array<[bigint, bigint, Principal]>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setTournamentResults(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setTournamentResults(arg0, arg1);
            return result;
        }
    }
    async submitOpenPaymentRequest(arg0: string, arg1: string, arg2: bigint, arg3: string, arg4: string, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitOpenPaymentRequest(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitOpenPaymentRequest(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async submitPaymentRequest(arg0: bigint, arg1: PaymentRequestType, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitPaymentRequest(arg0, to_candid_PaymentRequestType_n24(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitPaymentRequest(arg0, to_candid_PaymentRequestType_n24(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
    async unblockUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unblockUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unblockUser(arg0);
            return result;
        }
    }
    async updateOpenPaymentStatus(arg0: bigint, arg1: string, arg2: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOpenPaymentStatus(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOpenPaymentStatus(arg0, arg1, arg2);
            return result;
        }
    }
    async updatePaymentRequestStatus(arg0: bigint, arg1: PaymentRequestStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePaymentRequestStatus(arg0, to_candid_PaymentRequestStatus_n26(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePaymentRequestStatus(arg0, to_candid_PaymentRequestStatus_n26(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updatePhoneUserBalance(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePhoneUserBalance(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePhoneUserBalance(arg0, arg1);
            return result;
        }
    }
    async updatePhoneUserWinningCash(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePhoneUserWinningCash(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePhoneUserWinningCash(arg0, arg1);
            return result;
        }
    }
    async updateSettings(arg0: AppSettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSettings(arg0);
            return result;
        }
    }
}
function from_candid_PaymentRequestStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentRequestStatus): PaymentRequestStatus {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentRequestType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentRequestType): PaymentRequestType {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentRequest_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentRequest): PaymentRequest {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_TournamentStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TournamentStatus): TournamentStatus {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_TournamentView_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TournamentView): TournamentView {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PhoneUser]): PhoneUser | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AppSettings]): AppSettings | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    startTime: bigint;
    status: _TournamentStatus;
    title: string;
    minPlayers: bigint;
    playerCount: bigint;
    description: string;
    gameMode: string;
    entryFee: bigint;
    maxPlayers: bigint;
    prizePool: bigint;
}): {
    id: bigint;
    startTime: bigint;
    status: TournamentStatus;
    title: string;
    minPlayers: bigint;
    playerCount: bigint;
    description: string;
    gameMode: string;
    entryFee: bigint;
    maxPlayers: bigint;
    prizePool: bigint;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        status: from_candid_TournamentStatus_n17(_uploadFile, _downloadFile, value.status),
        title: value.title,
        minPlayers: value.minPlayers,
        playerCount: value.playerCount,
        description: value.description,
        gameMode: value.gameMode,
        entryFee: value.entryFee,
        maxPlayers: value.maxPlayers,
        prizePool: value.prizePool
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _PaymentRequestStatus;
    username: string;
    userId: Principal;
    note: string;
    timestamp: bigint;
    upiId: string;
    amount: bigint;
    requestType: _PaymentRequestType;
}): {
    id: bigint;
    status: PaymentRequestStatus;
    username: string;
    userId: Principal;
    note: string;
    timestamp: bigint;
    upiId: string;
    amount: bigint;
    requestType: PaymentRequestType;
} {
    return {
        id: value.id,
        status: from_candid_PaymentRequestStatus_n10(_uploadFile, _downloadFile, value.status),
        username: value.username,
        userId: value.userId,
        note: value.note,
        timestamp: value.timestamp,
        upiId: value.upiId,
        amount: value.amount,
        requestType: from_candid_PaymentRequestType_n12(_uploadFile, _downloadFile, value.requestType)
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    rejected: null;
} | {
    accepted: null;
}): PaymentRequestStatus {
    return "pending" in value ? PaymentRequestStatus.pending : "rejected" in value ? PaymentRequestStatus.rejected : "accepted" in value ? PaymentRequestStatus.accepted : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    withdraw: null;
} | {
    deposit: null;
}): PaymentRequestType {
    return "withdraw" in value ? PaymentRequestType.withdraw : "deposit" in value ? PaymentRequestType.deposit : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upcoming: null;
} | {
    complete: null;
} | {
    ongoing: null;
}): TournamentStatus {
    return "upcoming" in value ? TournamentStatus.upcoming : "complete" in value ? TournamentStatus.complete : "ongoing" in value ? TournamentStatus.ongoing : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TournamentView>): Array<TournamentView> {
    return value.map((x)=>from_candid_TournamentView_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PaymentRequest>): Array<PaymentRequest> {
    return value.map((x)=>from_candid_PaymentRequest_n8(_uploadFile, _downloadFile, x));
}
function to_candid_PaymentRequestStatus_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentRequestStatus): _PaymentRequestStatus {
    return to_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentRequestType_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentRequestType): _PaymentRequestType {
    return to_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function to_candid_TournamentStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TournamentStatus): _TournamentStatus {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_TransactionType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): _TransactionType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentRequestType): {
    withdraw: null;
} | {
    deposit: null;
} {
    return value == PaymentRequestType.withdraw ? {
        withdraw: null
    } : value == PaymentRequestType.deposit ? {
        deposit: null
    } : value;
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentRequestStatus): {
    pending: null;
} | {
    rejected: null;
} | {
    accepted: null;
} {
    return value == PaymentRequestStatus.pending ? {
        pending: null
    } : value == PaymentRequestStatus.rejected ? {
        rejected: null
    } : value == PaymentRequestStatus.accepted ? {
        accepted: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TournamentStatus): {
    upcoming: null;
} | {
    complete: null;
} | {
    ongoing: null;
} {
    return value == TournamentStatus.upcoming ? {
        upcoming: null
    } : value == TournamentStatus.complete ? {
        complete: null
    } : value == TournamentStatus.ongoing ? {
        ongoing: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): {
    deposit: null;
} | {
    withdrawal: null;
} {
    return value == TransactionType.deposit ? {
        deposit: null
    } : value == TransactionType.withdrawal ? {
        withdrawal: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
